import Footer from "app/layout/footer/footer";
import "app/styles/card.css";
import "app/globals.css";

export const metadata = {
  title: "Dꓘ",
  description: "a website generated by create next app by Danial Khakbaz.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen min-h-screen bg-black flex flex-col">
        <main className="grow">{children}</main>
        <footer className="flex flex-row flex-none justify-center items-center">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
