import { ReactNode } from "react";
import type { Metadata } from "next";
import Footer from "layout/footer/footer";
import { NunitoFont } from "theme/font";
import "styles/globals.css";

export const metadata: Metadata = {
  title: "DK | Danial Khakbaz",
  description: "a website generated by create next app by Danial Khakbaz.",
  icons: {
    icon: "/dk-logo-black.jpeg",
  },
  other: {
    "theme-color": "#000000",
    "color-scheme": "dark",
    "twitter:title": "",
    "twitter:description": "",
    "twitter:url": "",
    "twitter:domain": "",
    "twitter:image": "",
    "twitter:card": "summary_large_image",
    "og:title": "",
    "og:description": "",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
  },
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  return (
    <html className="bg-neutral-800 lg:bg-black" lang="en">
      <body
        className={`${NunitoFont.className} w-screen min-h-screen flex flex-col justify-center items-center`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
